# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script # 文字列比較
        timeout-minutes: 1
        run: |
          while true
          do
            result=echo "hoge"
            echo $result
            if [ "$result" = "hoge" ] # 終了条件
              break
            fi
            sleep 10 # 10秒後再実行
          done

      - name: Run a multi-line script
        timeout-minutes: 3
        run: |
          while true
          do
            result=echo $((RANDOM % 100)) # 0 - 99で乱数取得
            echo $result
            if [ $result -ge 80 ] # 80以上で終了
              break
            fi
            sleep 3 # 3秒後再実行
          done

      - name: Run a multi-line script # 達成不可能な条件でタイムアウトする
        timeout-minutes: 1
        run: |
          while true
          do
            result=echo $((RANDOM % 100)) # 0 - 99で乱数取得
            echo $result
            if [ $result -ge 9999 ] # 9999以上で終了(達成不可)
              break
            fi
            sleep 3 # 3秒後再実行
          done
